// Build script: presets/*.psdl.yaml → src/presets.generated.ts
//
// Validates each YAML file against the canonical PSDL 0.5 schema (resolved from
// @packet-schema/core — not vendored here), then emits a TS module exporting
// PRESETS: Record<string, Packet>. Run via `npm run build:presets` (also wired
// into prebuild / pretest).

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import { loadSchema, SCHEMA_VERSION } from "./schema.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const PRESETS_DIR = join(ROOT, "presets");
const OUT_PATH = join(ROOT, "src", "presets.generated.ts");

const FORMAT_VERSION = SCHEMA_VERSION;

type AjvError = { instancePath?: string; message?: string };

function keyFromFilename(file: string): string {
  return basename(file).replace(/\.psdl\.yaml$/, "");
}

function main(): void {
  const schema = loadSchema();

  const AjvCtor =
    (Ajv2020 as unknown as { default?: typeof Ajv2020 }).default ?? Ajv2020;
  const addFormatsFn =
    (addFormats as unknown as { default?: typeof addFormats }).default ??
    addFormats;
  const ajv = new AjvCtor({ allErrors: true, strict: false });
  addFormatsFn(ajv);
  const validate = ajv.compile(schema);

  const files = readdirSync(PRESETS_DIR)
    .filter((f) => f.endsWith(".psdl.yaml"))
    .sort()
    .map((f) => join(PRESETS_DIR, f));

  if (files.length === 0) {
    console.error(`No .psdl.yaml files found in ${PRESETS_DIR}`);
    process.exit(1);
  }

  const presets: Record<string, unknown> = {};
  let failed = false;

  for (const file of files) {
    const key = keyFromFilename(file);
    let raw: Record<string, unknown>;
    try {
      raw = parseYaml(readFileSync(file, "utf8")) as Record<string, unknown>;
    } catch (err) {
      console.error(`YAML parse error in ${basename(file)}: ${String(err)}`);
      failed = true;
      continue;
    }

    // Strip YAML anchors / merge keys that aren't part of the PSDL schema.
    const stripped = Object.fromEntries(
      Object.entries(raw).filter(([k]) => !k.startsWith("_")),
    );

    // PSDL 0.5 dropped the top-level `format` key and forbids unknown
    // top-level properties (unevaluatedProperties: false). Inject only the
    // version (if the file does not declare its own).
    const forValidation = { version: FORMAT_VERSION, ...stripped };
    if (!validate(forValidation)) {
      const errs = (validate.errors ?? [] as AjvError[])
        .map((e) => `  ${e.instancePath ?? ""}: ${e.message ?? ""}`)
        .join("\n");
      console.error(`Schema validation failed for ${basename(file)}:\n${errs}`);
      failed = true;
      continue;
    }

    presets[key] = stripped;
  }

  if (failed) process.exit(1);

  const src =
    "// AUTO-GENERATED by scripts/build.ts — DO NOT EDIT.\n" +
    "// Source: presets/*.psdl.yaml\n" +
    "import type { Packet } from \"@packet-schema/core\";\n\n" +
    "export const PRESETS: Record<string, Packet> = " +
    JSON.stringify(presets, null, 2) +
    " as unknown as Record<string, Packet>;\n";

  writeFileSync(OUT_PATH, src, "utf8");
  console.log(`Wrote src/presets.generated.ts (${files.length} presets).`);
}

main();
